dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- coverage run --branch --source=. ./manage.py test mixnet --keepdb
deploy:
  provider: heroku
  app: egc-app-practica7-alebarmor
  strategy: git
  api_key:
    secure: JDDMpRS0/FxU1PGveC5NzcS1qMc1wZIOVSEaBIfgh+Z4ix6NTPmYKtLFTWTyLLJJR8p6VU4qymg5IrvrqMW9a30CbJwT1z/1SZfcx2+YHOiz6zCZWRNBwkWhgdGIQw5UmaAuauEUabIHAdUvJLGEdxRGTvR9svWRU8xSrgRg2W0ykGEb2T1iw8RWGBWoMxXZLRLxg5URE0dS0rlfbMJd4p53pTNrmL/aQdC4fgF6YIUydZtc1S1WPKuMrEvdBHi90mwLybYBSFKWBWxyEq4iBXG95y9JaEgvVU3+ckAs3xrroBMUUEyZ/Yibiuu/JhcEdc6C00tBZr6+y/HABC913pF0sYqJPGlW5gFsVMGcw3N29cSSd+2+KNoyuKEKce3cFC04MRqL9R9Rupwic3EwC+/lRmS/WbvKPA2thbmaoxGpQS3Sm6F7RQfcReACffGbCWnDz1WS4jJubgMqNEdSQsvkKaaUv9fSCOZb51KRR5xAb24Shvr2+IV6LCy8/6EhEFRkNRYzkM5ccbBZ3hnTUBt/tiJGCRhe/zZpu70LRzAIJ+yUa+NEUivGV0vfCJsmam13QACI+ouWWwDN6W7vqc1WFcGanGqtmytSZnEUnYt79AqbzXDOIEmbm4zjEPkxRodhMdKNtI6hIdL4O6phpLhUBmQo4NI8HRMJ9o1Kn1s=
