dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- coverage run --branch --source=. ./manage.py test mixnet --keepdb
deploy:
  provider: heroku
  app: egc-app-practica7-alebarmor
  strategy: git
  api_key:
    secure: kpSa5W7r3MC8KjovIALWlH3pkdDlG+CFGzh7M2ned01l40avwvJ5J5DIic+LbVupMvvY5evL+C5axizObIVZU/GOjTTGcCL7feFrNaYAjR3JPUMFhu0mIwOMZbW9Iz7Ty2+g2w6HwS10i9sBQVxbCFVukblCtOFJBRIU0daivg8lk3m/3+tAAcd5KiInqUNJkxfM72JqwrjAM0KiHmUQddOKxGPU9c0XrUybtFY7KV1NA6MQ781gYWXYcRsYxdn7OFAPDDffR60mXzIYuCGJBZeSPGp+QqxyimdDRDmhadW18f+1ZHaOxzfAMtst8zTKP8fOc5kO8DYQZ3mzuB/GEfdVDGqW27SI01V9fW6pqtAo/8aiqigk0ikeZ967Q3Js5C+6eKjZzNRHzarbMmXz88zjF7ZssF7Qoo0zDUnKosmhDHyH0KYjElr6gEUt9UzzDUafOWPWoXx9HDC/qItbrFgixQwzKUOGtwDPMLFzEpz+9usZJpsVa8aPvhrMAU7iWSm2NG2vaJ+a8/lZt+geEeSqtB9xzXYSEJR8i+14Qk5quN5hjDsSS7YvEN9dQV7s1nRlpSawS6ayJa+9Y/M1XZfr/65NDG+A63r1f0EFxpz4nLPvJQ6I7/m6w2mJBDxR/232T/Z7dORIa8EaOhGbywIq2d5DYTdiqeuY0zdJSSw=
